version: '3'

services:

  backend:
    build: ./Backend

    ports:
      - "3000:3000"

    depends_on:
      - mysql

  frontend:
    build: ./Frontend

    ports:
      - "4200:4200"

  mysql:
    image: mysql:8

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login_app

    ports:
      - "3306:3306"

    volumes:
      - ./Backend/data/database.sql:/docker-entrypoint-initdb.d/database.sql